#1.SERVICES
services:
  #serivce_name1
  postgre:
    image : postgres : 16-alpine
    command: postgres -c shared_buffers=128MB
    container_name : cityfix_db
  #environment_variables aka values injected to the container
    environment:
      POSTGRES_DB: cityfix
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
  #ports user_pc : container
    ports:
    - "5432:5432"
  #volumes gives persistent storage
    volumes:
    - postgres_data:/var/lib/postgresql/data

  #service_name2
  backend:
    build: ./backend
    container_name : cityfix_api
  #ports user_id : container
    ports:
      - "8000:8000"

    depends_on:
      - postgres

volumes:
  postgres_data:

  
